/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ChargingRouteImport } from './routes/charging'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as RangeRouteImport } from './routes/range'
import { Route as SystemRouteImport } from './routes/system'
import { Route as ChargingIndexRouteImport } from './routes/charging.index'
import { Route as ChargingStationRouteImport } from './routes/charging.station'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargingRoute = ChargingRouteImport.update({
  id: '/charging',
  path: '/charging',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RangeRoute = RangeRouteImport.update({
  id: '/range',
  path: '/range',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargingIndexRoute = ChargingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChargingRoute,
} as any)
const ChargingStationRoute = ChargingStationRouteImport.update({
  id: '/station',
  path: '/station',
  getParentRoute: () => ChargingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/charging': typeof ChargingRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/range': typeof RangeRoute
  '/system': typeof SystemRoute
  '/charging/station': typeof ChargingStationRoute
  '/charging/': typeof ChargingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dashboard': typeof DashboardRoute
  '/range': typeof RangeRoute
  '/system': typeof SystemRoute
  '/charging/station': typeof ChargingStationRoute
  '/charging': typeof ChargingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/charging': typeof ChargingRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/range': typeof RangeRoute
  '/system': typeof SystemRoute
  '/charging/station': typeof ChargingStationRoute
  '/charging/': typeof ChargingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/charging'
    | '/dashboard'
    | '/range'
    | '/system'
    | '/charging/station'
    | '/charging/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/dashboard'
    | '/range'
    | '/system'
    | '/charging/station'
    | '/charging'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/charging'
    | '/dashboard'
    | '/range'
    | '/system'
    | '/charging/station'
    | '/charging/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ChargingRoute: typeof ChargingRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  RangeRoute: typeof RangeRoute
  SystemRoute: typeof SystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charging': {
      id: '/charging'
      path: '/charging'
      fullPath: '/charging'
      preLoaderRoute: typeof ChargingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/range': {
      id: '/range'
      path: '/range'
      fullPath: '/range'
      preLoaderRoute: typeof RangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charging/': {
      id: '/charging/'
      path: '/'
      fullPath: '/charging/'
      preLoaderRoute: typeof ChargingIndexRouteImport
      parentRoute: typeof ChargingRoute
    }
    '/charging/station': {
      id: '/charging/station'
      path: '/station'
      fullPath: '/charging/station'
      preLoaderRoute: typeof ChargingStationRouteImport
      parentRoute: typeof ChargingRoute
    }
  }
}

interface ChargingRouteChildren {
  ChargingStationRoute: typeof ChargingStationRoute
  ChargingIndexRoute: typeof ChargingIndexRoute
}

const ChargingRouteChildren: ChargingRouteChildren = {
  ChargingStationRoute: ChargingStationRoute,
  ChargingIndexRoute: ChargingIndexRoute,
}

const ChargingRouteWithChildren = ChargingRoute._addFileChildren(
  ChargingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ChargingRoute: ChargingRouteWithChildren,
  DashboardRoute: DashboardRoute,
  RangeRoute: RangeRoute,
  SystemRoute: SystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
